FROM apache/airflow:latest-python3.10
USER root
COPY requirements.txt .
RUN apt-get update && apt-get -y install libpq-dev gcc g++
USER airflow
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt